# Site settings
title: zhenpeng's
email: lizhen2096@163.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://layjump.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  layjump

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title.html
